### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by talegari** [traversc/trqwe#2]
Please consider releasing this on CRAN. I find this package useful.

**Reason**: Unless it is on CRAN, some official restrictions do not allow it to be used in serious work or production purposes.

**Suggestion**: A nice vignette with benchmarks will be appreciated.

**Comment by traversc** [comment]
I'm sorry, this will likely not be on CRAN.  Too many of the functions are not in a CRAN-acceptable format, and there would be a lot of work to create proper documentation.  

If you'd like to take some of the functions and drop it into a proper CRAN package, I'd be happy to help and/or be a contributor on it.  

(Feel free to re-open this issue)
